apiVersion: 1

datasources:
  - name: SQLite
    type: frser-sqlite-datasource
    access: proxy
    url: ""
    isDefault: true
    jsonData:
      path: "/var/lib/grafana/monitoring.db"
    secureJsonFields: {}
    version: 1
    editable: true