apiVersion: v1
kind: Service
metadata:
  name: nodejs-socket-service
  namespace: so1-fase2
  labels:
    app: nodejs-socket
    version: v1
spec:
  selector:
    app: nodejs-socket
  ports:
  - name: http
    port: 80
    targetPort: 4000
    protocol: TCP
  - name: websocket
    port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP