apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: so1-fase2
  labels:
    app: python-api
    version: v1
spec:
  selector:
    app: python-api
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
  type: ClusterIP