apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-api
  namespace: so1-fase2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-api
  template:
    metadata:
      labels:
        app: python-api
    spec:
      containers:
      - name: python-api
        image: marcoscruz2001/python-api:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "TU_CLOUD_SQL_IP"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "tu-password"
---
apiVersion: v1
kind: Service
metadata:
  name: python-api-service
  namespace: so1-fase2
spec:
  selector:
    app: python-api
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP