version: '3.8'

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-monitoring
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource,grafana-piechart-panel
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./monitoring.db:/var/lib/grafana/monitoring.db:ro
    restart: unless-stopped
    networks:
      - monitoring

  sqlite-web:
    image: coleifer/sqlite-web
    container_name: sqlite-web
    ports:
      - "8080:8080"
    volumes:
      - ./monitoring.db:/data/monitoring.db
    command: ["-H", "0.0.0.0", "-x", "/data/monitoring.db"]
    restart: unless-stopped
    networks:
      - monitoring

volumes:
  grafana-data:

networks:
  monitoring:
    driver: bridge